### ISSUE TITLE
[FEATURE] Upgrade CLI Experince

### ISSUE THREAD

**Issue by newtoallofthis123** [EFFLUX110/garuda#2]
Really great project! I tried it out and it's quite good. I love using and writing CLI's and believe that the CLI should be as pretty and non intimidating as possible. Hence, I would like to improve the project in the following ways

1. Add Rich Terminal Text support using [Rich](https://rich.readthedocs.io/)
2. Add more understandable user messages

The gist of it is that I want to make it look prettier. Let me know any specifics

Also, I would like to contribute to this under Hacktober Fest 2023, so would you kindly add `hacktoberfest` to your repo?

**Comment by Mrinank-Bhowmick** [comment]
Yeah sure, I was also looking for someone who can make a better CLI.
Assigning the issue to you but if you want to make your pull request valid for hacktoberfest make sure you do it between 1-30 October.

**Comment by newtoallofthis123** [comment]
Sure! Thanks

**Comment by newtoallofthis123** [comment]
Hey @Mrinank-Bhowmick! Can you please add the `hacktoberfest` label to the project so that this contribution can count towards my hacktober journey.

Btw, this is how the output looks. I'll send a PR after you kindly add the label. Thanks!

![image](https://github.com/Mrinank-Bhowmick/garuda/assets/78465651/ce44a396-2bbf-4e43-a8fe-be28e8715d45)

**Comment by Mrinank-Bhowmick** [comment]
> Hey @Mrinank-Bhowmick! Can you please add the `hacktoberfest` label to the project so that this contribution can count towards my hacktober journey.
> 
> Btw, this is how the output looks. I'll send a PR after you kindly add the label. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/78465651/271810929-ce44a396-2bbf-4e43-a8fe-be28e8715d45.png)

amazing ⭐

**Comment by newtoallofthis123** [comment]
So sorry but @Mrinank-Bhowmick can you please add the `hacktoberfest` label to the whole repo. Apparently issues don't count. 😅

**Comment by Mrinank-Bhowmick** [comment]
> So sorry but @Mrinank-Bhowmick can you please add the `hacktoberfest` label to the whole repo. Apparently issues don't count. 😅 

Ahh ok wait

**Comment by newtoallofthis123** [comment]
Thanks! Will open the PR in a bit 😄

**Comment by Mrinank-Bhowmick** [comment]
Merged 🎉😀

**Comment by newtoallofthis123** [comment]
Cool! 😄
